"""Add trx_balance field to TronRequest model

Revision ID: 606c712cf0b8
Revises: 8a0935ae4933
Create Date: 2025-03-29 06:45:26.961301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606c712cf0b8'
down_revision: Union[str, None] = '8a0935ae4933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tron_request', sa.Column('trx_balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tron_request', 'trx_balance')
    # ### end Alembic commands ###
